# Generated by Django 5.2.4 on 2025-08-28 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('blood_type', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_donation', models.DateField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donors.donor')),
            ],
        ),
    ]
